frase = '  Curso em video python  '
#len(frase)
#frase[9::3]
frase.count('o')
#print(frase.count('o'))
frase.find('deo')
#print(frase.find('deo'))
frase.find('Android')
#print(frase.find('Android'))
frase.replace('python', 'Android')
#print(frase.replace('python', 'Android'))
frase.upper()
#print(frase.upper())
frase.lower()
#print(frase.lower())
frase.capitalize()
#print(frase.capitalize())
frase.title()
#print(frase.title())
frase.strip()
#print(frase.strip())
frase.rstrip()
frase.lstrip()
frase.split()
#print(frase.split())
'-'.join(frase)
print('-'.join(frase))
print('-'.join(frase))
print('-'.join(frase))

