n = input('Type Something: ')
print('What primitive type of this value: ', type(n))
print('Its just a number?:', n.isnumeric())
print('Its alphabetcial?' ,n.isalpha())
print('Its alphanumeric?' ,n.isalnum())
print('there are only spaces?',n.isspace())
print('its lowercase?' ,n.islower())
print('its in capital letters?' ,n.isupper())
print('its capitalize?' ,n.istitle())
